name = "codelabs"
license = "APACHE"
licenselink = "https://www.apache.org/licenses/LICENSE-2.0"
description = "A hugo theme of Google's codelabs."
homepage = "https://deep-diver.github.io/codelabs.github.io/"
tags = ["codelabs","syntax highlighting"]
min_version = "0.31"

[author]
  name = "chansung park"
  homepage = "https://github.com/deep-diver"
