# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://gde-codelabs.github.io/"

title = "Tutorials made by GDEs"
languageCode = "en-us"
theme = "codelabs"

[params]
  homeTitle = "Tutorials made by GDEs!"
  homeDescription = """
This page delivers Tutorials made by GDEs ([Google Developers Experts](https://developers.google.com/programs/experts/)). We cover broad range
of topics including Google Cloud, Android, Firebase, TensorFlow, and so on.

If you'd like to see a tutorial written on a specific topic, [let us know](#).
"""
  footer = "<a href=\"https://github.com/nekocode/codelabs-hugo-theme\">❤ Source code</a>"
  feedbackLink = "mailto:nekocode.cn@gmail.com"
  [params.categoryColors]
    mlops = "#1A73E8"
    tfx = "#f58442"
    gcp = "#3884ff"
